# Copyright (c) 2024 Qualcomm Technologies, Inc.
# All Rights Reserved.

from clevr_skills.utils.paths import PACKAGE_ASSET_DIR

VT_DIR = PACKAGE_ASSET_DIR / "vima_textures"

_COLORS = {
    "red": (1.0, 0.0, 0.0),
    "green": (0.0, 1.0, 0.0),
    "blue": (0.0, 0.0, 1.0),
    "yellow": (1.0, 1.0, 0.0),
    "purple": (1.0, 0.0, 1.0),
    "cyan": (0.0, 1.0, 1.0),
    "white": (1.0, 1.0, 1.0),
    "black": (0.2, 0.2, 0.2),
    "grey": (0.5, 0.5, 0.5),
}

_TEXTURES = {
    "brick": VT_DIR / "brick.jpg",
    "checkerboard": VT_DIR / "checkerboard.png",
    "granite": VT_DIR / "granite.png",
    "magma": VT_DIR / "magma.jpg",
    "black paisley": VT_DIR / "paisley.jpg",
    "plastic": VT_DIR / "plastic.jpg",
    "black white polka dot": VT_DIR / "polka_dot.jpg",
    "rainbow": VT_DIR / "rainbow.jpg",
    "swirl": VT_DIR / "swirl.jpg",
    "tiger": VT_DIR / "tiger.jpg",
    "tiled": VT_DIR / "tiles.jpg",
    "wooden": VT_DIR / "wood_light.png",
    "blue paisley": VT_DIR / "paisleys" / "blue_paisley.jpg",
    "green paisley": VT_DIR / "paisleys" / "green_paisley.jpg",
    "purple paisley": VT_DIR / "paisleys" / "purple_paisley.jpg",
    "red paisley": VT_DIR / "paisleys" / "red_paisley.jpg",
    "yellow paisley": VT_DIR / "paisleys" / "yellow_paisley.jpg",
    "blue purple polka dot": VT_DIR / "polka_dots" / "blue_purple_polka_dot.jpg",
    "dark blue purple polka dot": VT_DIR / "polka_dots" / "dark_blue_purple_polka_dot.jpg",
    "dark green blue polka dot": VT_DIR / "polka_dots" / "dark_green_blue_polka_dot.jpg",
    "dark green purple polka dot": VT_DIR / "polka_dots" / "dark_green_purple_polka_dot.jpg",
    "dark red_blue polka dot": VT_DIR / "polka_dots" / "dark_red_blue_polka_dot.jpg",
    "dark red green polka dot": VT_DIR / "polka_dots" / "dark_red_green_polka_dot.jpg",
    "dark red purple polka dot": VT_DIR / "polka_dots" / "dark_red_purple_polka_dot.jpg",
    "dark red yellow polka dot": VT_DIR / "polka_dots" / "dark_red_yellow_polka_dot.jpg",
    "dark yellow blue polka dot": VT_DIR / "polka_dots" / "dark_yellow_blue_polka_dot.jpg",
    "dark yellow green polka dot": VT_DIR / "polka_dots" / "dark_yellow_green_polka_dot.jpg",
    "dark yellow purple polka dot": VT_DIR / "polka_dots" / "dark_yellow_purple_polka_dot.jpg",
    "green blue polka dot": VT_DIR / "polka_dots" / "green_blue_polka_dot.jpg",
    "green purple polka dot": VT_DIR / "polka_dots" / "green_purple_polka_dot.jpg",
    "red blue polka dot": VT_DIR / "polka_dots" / "red_blue_polka_dot.jpg",
    "red green polka dot": VT_DIR / "polka_dots" / "red_green_polka_dot.jpg",
    "red purple polka dot": VT_DIR / "polka_dots" / "red_purple_polka_dot.jpg",
    "red yellow polka dot": VT_DIR / "polka_dots" / "red_yellow_polka_dot.jpg",
    "yellow blue polka dot": VT_DIR / "polka_dots" / "yellow_blue_polka_dot.jpg",
    "yellow green polka dot": VT_DIR / "polka_dots" / "yellow_green_polka_dot.jpg",
    "yellow purple polka dot": VT_DIR / "polka_dots" / "yellow_purple_polka_dot.jpg",
    "blue purple stripe": VT_DIR / "stripes" / "blue_purple_stripe.jpg",
    "dark blue_purple stripe": VT_DIR / "stripes" / "dark_blue_purple_stripe.jpg",
    "dark green_blue stripe": VT_DIR / "stripes" / "dark_green_blue_stripe.jpg",
    "dark green_purple stripe": VT_DIR / "stripes" / "dark_green_purple_stripe.jpg",
    "dark red blue stripe": VT_DIR / "stripes" / "dark_red_blue_stripe.jpg",
    "dark red green stripe": VT_DIR / "stripes" / "dark_red_green_stripe.jpg",
    "dark red purple stripe": VT_DIR / "stripes" / "dark_red_purple_stripe.jpg",
    "dark red yellow stripe": VT_DIR / "stripes" / "dark_red_yellow_stripe.jpg",
    "dark yellow_blue stripe": VT_DIR / "stripes" / "dark_yellow_blue_stripe.jpg",
    "dark yellow_green stripe": VT_DIR / "stripes" / "dark_yellow_green_stripe.jpg",
    "dark yellow_purple stripe": VT_DIR / "stripes" / "dark_yellow_purple_stripe.jpg",
    "green blue stripe": VT_DIR / "stripes" / "green_blue_stripe.jpg",
    "green purple stripe": VT_DIR / "stripes" / "green_purple_stripe.jpg",
    "red blue stripe": VT_DIR / "stripes" / "red_blue_stripe.jpg",
    "red green stripe": VT_DIR / "stripes" / "red_green_stripe.jpg",
    "red purple stripe": VT_DIR / "stripes" / "red_purple_stripe.jpg",
    "red yellow stripe": VT_DIR / "stripes" / "red_yellow_stripe.jpg",
    "yellow blue stripe": VT_DIR / "stripes" / "yellow_blue_stripe.jpg",
    "yellow green stripe": VT_DIR / "stripes" / "yellow_green_stripe.jpg",
    "yellow purple stripe": VT_DIR / "stripes" / "yellow_purple_stripe.jpg",
    "blue swirl": VT_DIR / "swirls" / "blue_swirl.jpg",
    "dark blue swirl": VT_DIR / "swirls" / "dark_blue_swirl.jpg",
    "dark green swirl": VT_DIR / "swirls" / "dark_green_swirl.jpg",
    "dark purple swirl": VT_DIR / "swirls" / "dark_purple_swirl.jpg",
    "dark red swirl": VT_DIR / "swirls" / "dark_red_swirl.jpg",
    "dark yellow swirl": VT_DIR / "swirls" / "dark_yellow_swirl.jpg",
    "green swirl": VT_DIR / "swirls" / "green_swirl.jpg",
    "purple swirl": VT_DIR / "swirls" / "purple_swirl.jpg",
    "red swirl": VT_DIR / "swirls" / "red_swirl.jpg",
    "yellow swirl": VT_DIR / "swirls" / "yellow_swirl.jpg",
}


_COLORS_AND_TEXTURES = _COLORS | _TEXTURES
